In [1]:
x = -3
print(x)

-3

In [2]:
type(x)

int

In [3]:
# wap to add two number 
x = 22
y = 22   
z = x+y
print(z)

44

In [6]:
#+, -, *,/

# +, -, *,/ ---- >arithmetic number

a= 10
b = 5
c = a//b
print(c)

2

In [5]:
a =10
b =4
c = a*b
##absolute answer given here
print(c)

40

In [7]:
#%----> mod operator 

z = 11
b = 22
x = z%b
print(x)

11

# user input

In [1]:
y = input('enter something')
print(y)

enter somethingjwjdeiekdelkekd
jwjdeiekdelkekd

In [2]:
# wap to add two numbers with the help of user input..
x = int(input("enter the first number"))
y = int(input("enter the second number"))
z = x+y
print(z)

enter the first number33
enter the second number44
77

In [5]:
## concatenation 
x ='3'
b = 'n'
c = x+b
print(c)

3n

In [4]:
x = int(input("enter the first number"))
y = int(input("enter the second number"))
z = x*y
print(z)

enter the first number38339302
enter the second number84849493
3253070336673886

In [6]:
x = int(input("enter the first number"))
y = float(input("enter the second number"))
z = x*y
print(z)

enter the first number9222383
enter the second number39.9933
368833530.03389996

In [17]:
# >,<,>=,<=,==,!=
# conditional operator------->

# synatx---->if/else
#if condition
#print (msg)
#else:
#print(msg

age = 18
if age>18:
    print("Adult")
elif age == 18:
    print('teeneger')
else:
    print('baby')

teeneger

In [9]:
age = 90
if age>18:
    print(" old person")

 old person

In [18]:
# a company  decided to give  bonus
# of 5% to employee if his/ her year of services is more than 5 year
 # ask user for their salary and year of services and print 
    # the next bonus amount 
    
salary = 39393383;
year_of_service = 30
if year_of_service>5:
    bonus = (salary*5)/100
    print("bonus",bonus)
else:
    print('NO BONUS')

bonus 1969669.15

In [20]:
salary = int(input("enter your salary"))
year_of_service = int(input("enter your service"))

if year_of_service>5:
    bonus = (salary*5)/100
    print("bonus",bonus)
else:
    print('NO BONUS')

enter your salary80000
enter your service4
NO BONUS

# 8 june lecture

In [25]:
# wap two take a integer in greater than value

x = int(input("enter the first number"))
y = int(input("enter the second number"))
if a>b:
    print(" a is greater")
else:
    print('b is smaller')

enter the first number27
enter the second number3
b is smaller

In [27]:
# max of three numbers
a = int(input("first num"))
b = int(input("second num"))
c = int(input("third num"))

if a>b and a>c:
    print("A is greater")
elif b>a and b>c :
    print("B is greater")
elif c>a and c>b:
    print("c is greater")

first num33
second num94
third num89
B is greater

In [28]:
# min of three numbers
a = int(input("first num"))
b = int(input("second num"))
c = int(input("third num"))

if a<b and a<c:
    print("A is smaller")
elif b<a and b<c :
    print("B is smaller")
elif c<a and c<b:
    print("c is smaller")

first num44
second num15
third num3
c is smaller

In [32]:
# a shop will give discount of 10% if the cost of purchased quantity is more than 1000.
# ask user for quantity 
# suppose , one unit will cost 100.
# judge and print total cost for user 

unit_cost = 100
unit_purchase = 20
price = unit_cost * unit_purchase
if price > 1000:
    discount = (price*10)/100
    excat_amount_paid = price - discount
    print("your discount is ------->",discount)
    print("your excat price to be paid------->", excat_amount_paid)
        
else: 
    print("no discount")

your discount is -------> 200.0
your excat price to be paid-------> 1800.0

In [33]:
unit_cost = int(input("enter the unit cost"))
unit_purchase = int(input("enter the unit purchase"))
price = unit_cost * unit_purchase
if price > 1000:
    discount = (price*10)/100
    excat_amount_paid = price - discount
    print("your discount is ------->",discount)
    print("your excat price to be paid------->", excat_amount_paid)
        
else: 
    print("no discount")

enter the unit cost67777
enter the unit purchase5
your discount is -------> 33888.5
your excat price to be paid-------> 304996.5

In [2]:
unit_cost = int(input("enter the unit cost"))
unit_purchase = int(input("enter the unit purchase"))
price = unit_cost *unit_purchase
if price > 20000:
    discount = (price*10)/100
    excat_amount_paid = price- disount
    print("your discount is------->", discount)
    print("your excat price to be paid------>", exact_amount_paid)
    
else:  
    print("no discount")

enter the unit cost1000
enter the unit purchase5
no discount

In [6]:
# A school has following rules for grading system :
#a . below 25 -f
# b . 25 to 45 -E
# c . 45 to 50 - D
# d.  50 to 60  - C
# e.  60to 80 - B
# f. above 80 -A
# ask user to enter marks and print the corresponding grade.


marks = int(input("enter your marks!!"))
if marks >80:
    print(" A grade")
elif marks>60 and marks<80:
    print("b grade")
elif marks > 50 and marks<=60:
     print("c grade")
elif marks > 45 and marks<= 50:
    print("D grade")
elif marks > 25 and marks<= 45:
    print("E grade")
elif marks<25 :
    print("f grade")

enter your marks!!67
b grade

In [7]:
#take input of age of  3 people by user and determine oldest and youngest among tham

age = int(input("enter the age"))
if age>18:
    print(" old")
else:
    print('young')

enter the age30
 old

In [8]:
# A student will not be allowed to sit in exam 
# if his/her attendance is less than 75%.
# Take following input from user
# Number of classes held
# Number of classes attended.
# And print
# percentage of class attended
# Is student is allowed to sit in exam or not.

num_of_class_held = int(input("Enter the class held"))
num_of_class_attend = int(input("Number of class attend"))

per_of_class_attend = (num_of_class_attend*100)/num_of_class_held

if per_of_class_attend<75:
    medical_condition = input("Do you have any medical condition for yes type Y and for no type N")
    if medical_condition == 'Y':
        print("Allowed due to medical condition")
    else:
        print("Not Allowed")
    
else:
    print("Allowed")
print(per_of_class_attend)

Enter the class held120
Number of class attend67
Do you have any medical condition for yes type Y and for no type N6
Not Allowed
55.833333333333336

In [34]:
# wap to determine the salary if a person takes more than 12 leave in a year 
# then he/she will get a salary cut of 7%  but if the leave is less in 
# number then
# he/she  will receive a bonus of 20%. if the employee is onboard then he/she 
# will  get more than 12 leaves and a bonus of 12% with increment of 5% 
# in salary .

leave = int(input("enter the number of your holidays"))
onboard = input("Are you onboard for yes 'Y' for no type 'N'")
salary = int(input('Enter the salary'))
if leave>12:
    sal_cut = (salary *7)/100
    recieve_amt_after_cut = salary - sal_cut
    print(recieve_amt_after_cut)
    if onboard == 'Y':
        extra_income = (salary*17)/100
        print(extra_income)
else:
    bonus = (salary*20)/100
    recieve_amt_after_bonus = salary+bonus
    print(recieve_amt_after_bonus)

enter the number of your holidays23
Are you onboard for yes 'Y' for no type 'N'N
Enter the salary100000
93000.0

# loop

In [26]:
# 1- 10
# use loop 

# 1 for loop----> no of iteration / no of repeation is known 
# 2 while loop-----> no of iteration/ no of repeation known or unknown.

# 1-10 
#for loop
# syntax for loop
#for var in range():
  #  print(var)
for i in range(15):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14

In [31]:
for i in range(2,10):
    print(i)

2
3
4
5
6
7
8
9

In [33]:
# alternate number
for i in range(1,21,4):
    print(i)

1
5
9
13
17

In [35]:
# while loop 
# step -1 initalization
# step-2 condition 
# step -3 decrement / increment

x = 2
while x<10:
    print(x)
    x = x+1
#     x+=1
#     x++

2
3
4
5
6
7
8
9

In [36]:
# wap to print from -10 to 10
# wap to print from 10 to -10.
# wap to print odd and even number upto 100
# wap to find prime numbers upto 20 terms.
#wap to find fibonacci series upto 12 terms.
# wap to print a pattern
# *
# **
# ***
# ****
# *****
# where row = 5
# wap to reverse a string.
#wap to find a word is palindrome or not.

for i in range(10,-11,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1
0
-1
-2
-3
-4
-5
-6
-7
-8
-9
-10

# 13 june

In [38]:
for i in range(1,1000):
    if i % 2 == 0:
        print('Even number',i)
    else:
        print('Odd number')

Odd number
Even number 2
Odd number
Even number 4
Odd number
Even number 6
Odd number
Even number 8
Odd number
Even number 10
Odd number
Even number 12
Odd number
Even number 14
Odd number
Even number 16
Odd number
Even number 18
Odd number
Even number 20
Odd number
Even number 22
Odd number
Even number 24
Odd number
Even number 26
Odd number
Even number 28
Odd number
Even number 30
Odd number
Even number 32
Odd number
Even number 34
Odd number
Even number 36
Odd number
Even number 38
Odd number
Even number 40
Odd number
Even number 42
Odd number
Even number 44
Odd number
Even number 46
Odd number
Even number 48
Odd number
Even number 50
Odd number
Even number 52
Odd number
Even number 54
Odd number
Even number 56
Odd number
Even number 58
Odd number
Even number 60
Odd number
Even number 62
Odd number
Even number 64
Odd number
Even number 66
Odd number
Even number 68
Odd number
Even number 70
Odd number
Even number 72
Odd number
Even number 74
Odd number
Even number 76
Odd number
Even number 78
Odd number
Even number 80
Odd number
Even number 82
Odd number
Even number 84
Odd number
Even number 86
Odd number
Even number 88
Odd number
Even number 90
Odd number
Even number 92
Odd number
Even number 94
Odd number
Even number 96
Odd number
Even number 98
Odd number
Even number 100
Odd number
Even number 102
Odd number
Even number 104
Odd number
Even number 106
Odd number
Even number 108
Odd number
Even number 110
Odd number
Even number 112
Odd number
Even number 114
Odd number
Even number 116
Odd number
Even number 118
Odd number
Even number 120
Odd number
Even number 122
Odd number
Even number 124
Odd number
Even number 126
Odd number
Even number 128
Odd number
Even number 130
Odd number
Even number 132
Odd number
Even number 134
Odd number
Even number 136
Odd number
Even number 138
Odd number
Even number 140
Odd number
Even number 142
Odd number
Even number 144
Odd number
Even number 146
Odd number
Even number 148
Odd number
Even number 150
Odd number
Even number 152
Odd number
Even number 154
Odd number
Even number 156
Odd number
Even number 158
Odd number
Even number 160
Odd number
Even number 162
Odd number
Even number 164
Odd number
Even number 166
Odd number
Even number 168
Odd number
Even number 170
Odd number
Even number 172
Odd number
Even number 174
Odd number
Even number 176
Odd number
Even number 178
Odd number
Even number 180
Odd number
Even number 182
Odd number
Even number 184
Odd number
Even number 186
Odd number
Even number 188
Odd number
Even number 190
Odd number
Even number 192
Odd number
Even number 194
Odd number
Even number 196
Odd number
Even number 198
Odd number
Even number 200
Odd number
Even number 202
Odd number
Even number 204
Odd number
Even number 206
Odd number
Even number 208
Odd number
Even number 210
Odd number
Even number 212
Odd number
Even number 214
Odd number
Even number 216
Odd number
Even number 218
Odd number
Even number 220
Odd number
Even number 222
Odd number
Even number 224
Odd number
Even number 226
Odd number
Even number 228
Odd number
Even number 230
Odd number
Even number 232
Odd number
Even number 234
Odd number
Even number 236
Odd number
Even number 238
Odd number
Even number 240
Odd number
Even number 242
Odd number
Even number 244
Odd number
Even number 246
Odd number
Even number 248
Odd number
Even number 250
Odd number
Even number 252
Odd number
Even number 254
Odd number
Even number 256
Odd number
Even number 258
Odd number
Even number 260
Odd number
Even number 262
Odd number
Even number 264
Odd number
Even number 266
Odd number
Even number 268
Odd number
Even number 270
Odd number
Even number 272
Odd number
Even number 274
Odd number
Even number 276
Odd number
Even number 278
Odd number
Even number 280
Odd number
Even number 282
Odd number
Even number 284
Odd number
Even number 286
Odd number
Even number 288
Odd number
Even number 290
Odd number
Even number 292
Odd number
Even number 294
Odd number
Even number 296
Odd number
Even number 298
Odd number
Even number 300
Odd number
Even number 302
Odd number
Even number 304
Odd number
Even number 306
Odd number
Even number 308
Odd number
Even number 310
Odd number
Even number 312
Odd number
Even number 314
Odd number
Even number 316
Odd number
Even number 318
Odd number
Even number 320
Odd number
Even number 322
Odd number
Even number 324
Odd number
Even number 326
Odd number
Even number 328
Odd number
Even number 330
Odd number
Even number 332
Odd number
Even number 334
Odd number
Even number 336
Odd number
Even number 338
Odd number
Even number 340
Odd number
Even number 342
Odd number
Even number 344
Odd number
Even number 346
Odd number
Even number 348
Odd number
Even number 350
Odd number
Even number 352
Odd number
Even number 354
Odd number
Even number 356
Odd number
Even number 358
Odd number
Even number 360
Odd number
Even number 362
Odd number
Even number 364
Odd number
Even number 366
Odd number
Even number 368
Odd number
Even number 370
Odd number
Even number 372
Odd number
Even number 374
Odd number
Even number 376
Odd number
Even number 378
Odd number
Even number 380
Odd number
Even number 382
Odd number
Even number 384
Odd number
Even number 386
Odd number
Even number 388
Odd number
Even number 390
Odd number
Even number 392
Odd number
Even number 394
Odd number
Even number 396
Odd number
Even number 398
Odd number
Even number 400
Odd number
Even number 402
Odd number
Even number 404
Odd number
Even number 406
Odd number
Even number 408
Odd number
Even number 410
Odd number
Even number 412
Odd number
Even number 414
Odd number
Even number 416
Odd number
Even number 418
Odd number
Even number 420
Odd number
Even number 422
Odd number
Even number 424
Odd number
Even number 426
Odd number
Even number 428
Odd number
Even number 430
Odd number
Even number 432
Odd number
Even number 434
Odd number
Even number 436
Odd number
Even number 438
Odd number
Even number 440
Odd number
Even number 442
Odd number
Even number 444
Odd number
Even number 446
Odd number
Even number 448
Odd number
Even number 450
Odd number
Even number 452
Odd number
Even number 454
Odd number
Even number 456
Odd number
Even number 458
Odd number
Even number 460
Odd number
Even number 462
Odd number
Even number 464
Odd number
Even number 466
Odd number
Even number 468
Odd number
Even number 470
Odd number
Even number 472
Odd number
Even number 474
Odd number
Even number 476
Odd number
Even number 478
Odd number
Even number 480
Odd number
Even number 482
Odd number
Even number 484
Odd number
Even number 486
Odd number
Even number 488
Odd number
Even number 490
Odd number
Even number 492
Odd number
Even number 494
Odd number
Even number 496
Odd number
Even number 498
Odd number
Even number 500
Odd number
Even number 502
Odd number
Even number 504
Odd number
Even number 506
Odd number
Even number 508
Odd number
Even number 510
Odd number
Even number 512
Odd number
Even number 514
Odd number
Even number 516
Odd number
Even number 518
Odd number
Even number 520
Odd number
Even number 522
Odd number
Even number 524
Odd number
Even number 526
Odd number
Even number 528
Odd number
Even number 530
Odd number
Even number 532
Odd number
Even number 534
Odd number
Even number 536
Odd number
Even number 538
Odd number
Even number 540
Odd number
Even number 542
Odd number
Even number 544
Odd number
Even number 546
Odd number
Even number 548
Odd number
Even number 550
Odd number
Even number 552
Odd number
Even number 554
Odd number
Even number 556
Odd number
Even number 558
Odd number
Even number 560
Odd number
Even number 562
Odd number
Even number 564
Odd number
Even number 566
Odd number
Even number 568
Odd number
Even number 570
Odd number
Even number 572
Odd number
Even number 574
Odd number
Even number 576
Odd number
Even number 578
Odd number
Even number 580
Odd number
Even number 582
Odd number
Even number 584
Odd number
Even number 586
Odd number
Even number 588
Odd number
Even number 590
Odd number
Even number 592
Odd number
Even number 594
Odd number
Even number 596
Odd number
Even number 598
Odd number
Even number 600
Odd number
Even number 602
Odd number
Even number 604
Odd number
Even number 606
Odd number
Even number 608
Odd number
Even number 610
Odd number
Even number 612
Odd number
Even number 614
Odd number
Even number 616
Odd number
Even number 618
Odd number
Even number 620
Odd number
Even number 622
Odd number
Even number 624
Odd number
Even number 626
Odd number
Even number 628
Odd number
Even number 630
Odd number
Even number 632
Odd number
Even number 634
Odd number
Even number 636
Odd number
Even number 638
Odd number
Even number 640
Odd number
Even number 642
Odd number
Even number 644
Odd number
Even number 646
Odd number
Even number 648
Odd number
Even number 650
Odd number
Even number 652
Odd number
Even number 654
Odd number
Even number 656
Odd number
Even number 658
Odd number
Even number 660
Odd number
Even number 662
Odd number
Even number 664
Odd number
Even number 666
Odd number
Even number 668
Odd number
Even number 670
Odd number
Even number 672
Odd number
Even number 674
Odd number
Even number 676
Odd number
Even number 678
Odd number
Even number 680
Odd number
Even number 682
Odd number
Even number 684
Odd number
Even number 686
Odd number
Even number 688
Odd number
Even number 690
Odd number
Even number 692
Odd number
Even number 694
Odd number
Even number 696
Odd number
Even number 698
Odd number
Even number 700
Odd number
Even number 702
Odd number
Even number 704
Odd number
Even number 706
Odd number
Even number 708
Odd number
Even number 710
Odd number
Even number 712
Odd number
Even number 714
Odd number
Even number 716
Odd number
Even number 718
Odd number
Even number 720
Odd number
Even number 722
Odd number
Even number 724
Odd number
Even number 726
Odd number
Even number 728
Odd number
Even number 730
Odd number
Even number 732
Odd number
Even number 734
Odd number
Even number 736
Odd number
Even number 738
Odd number
Even number 740
Odd number
Even number 742
Odd number
Even number 744
Odd number
Even number 746
Odd number
Even number 748
Odd number
Even number 750
Odd number
Even number 752
Odd number
Even number 754
Odd number
Even number 756
Odd number
Even number 758
Odd number
Even number 760
Odd number
Even number 762
Odd number
Even number 764
Odd number
Even number 766
Odd number
Even number 768
Odd number
Even number 770
Odd number
Even number 772
Odd number
Even number 774
Odd number
Even number 776
Odd number
Even number 778
Odd number
Even number 780
Odd number
Even number 782
Odd number
Even number 784
Odd number
Even number 786
Odd number
Even number 788
Odd number
Even number 790
Odd number
Even number 792
Odd number
Even number 794
Odd number
Even number 796
Odd number
Even number 798
Odd number
Even number 800
Odd number
Even number 802
Odd number
Even number 804
Odd number
Even number 806
Odd number
Even number 808
Odd number
Even number 810
Odd number
Even number 812
Odd number
Even number 814
Odd number
Even number 816
Odd number
Even number 818
Odd number
Even number 820
Odd number
Even number 822
Odd number
Even number 824
Odd number
Even number 826
Odd number
Even number 828
Odd number
Even number 830
Odd number
Even number 832
Odd number
Even number 834
Odd number
Even number 836
Odd number
Even number 838
Odd number
Even number 840
Odd number
Even number 842
Odd number
Even number 844
Odd number
Even number 846
Odd number
Even number 848
Odd number
Even number 850
Odd number
Even number 852
Odd number
Even number 854
Odd number
Even number 856
Odd number
Even number 858
Odd number
Even number 860
Odd number
Even number 862
Odd number
Even number 864
Odd number
Even number 866
Odd number
Even number 868
Odd number
Even number 870
Odd number
Even number 872
Odd number
Even number 874
Odd number
Even number 876
Odd number
Even number 878
Odd number
Even number 880
Odd number
Even number 882
Odd number
Even number 884
Odd number
Even number 886
Odd number
Even number 888
Odd number
Even number 890
Odd number
Even number 892
Odd number
Even number 894
Odd number
Even number 896
Odd number
Even number 898
Odd number
Even number 900
Odd number
Even number 902
Odd number
Even number 904
Odd number
Even number 906
Odd number
Even number 908
Odd number
Even number 910
Odd number
Even number 912
Odd number
Even number 914
Odd number
Even number 916
Odd number
Even number 918
Odd number
Even number 920
Odd number
Even number 922
Odd number
Even number 924
Odd number
Even number 926
Odd number
Even number 928
Odd number
Even number 930
Odd number
Even number 932
Odd number
Even number 934
Odd number
Even number 936
Odd number
Even number 938
Odd number
Even number 940
Odd number
Even number 942
Odd number
Even number 944
Odd number
Even number 946
Odd number
Even number 948
Odd number
Even number 950
Odd number
Even number 952
Odd number
Even number 954
Odd number
Even number 956
Odd number
Even number 958
Odd number
Even number 960
Odd number
Even number 962
Odd number
Even number 964
Odd number
Even number 966
Odd number
Even number 968
Odd number
Even number 970
Odd number
Even number 972
Odd number
Even number 974
Odd number
Even number 976
Odd number
Even number 978
Odd number
Even number 980
Odd number
Even number 982
Odd number
Even number 984
Odd number
Even number 986
Odd number
Even number 988
Odd number
Even number 990
Odd number
Even number 992
Odd number
Even number 994
Odd number
Even number 996
Odd number
Even number 998
Odd number

In [39]:
#wap to find prime number.

num = int(input("Enter the number"))
if num>1:
    for i in range(2,num):
        if num % i == 0 :
            print(num,"Not the prime number")
            break
            
        else:
            print(num,"Prime number")
else:
    print(num,"not prime number")

Enter the number8
8 Not the prime number

In [40]:
n1 = 0
n2 = 1
count = 0
nterms = 12
if nterms<=0:
    print("Enter a valid int")
elif nterms == 1:
    print(n1)
    
# else:
while count<nterms:
    print(n1)
    nth = n1+n2
    n1=n2
    n2=nth
    count = count+1

0
1
1
2
3
5
8
13
21
34
55
89